[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bun run src/server.ts & bun run src/index.ts"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
aptPkgs = [
    "fonts-liberation",
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libatspi2.0-0",
    "libcups2",
    "libdbus-1-3",
    "libdrm2",
    "libgbm1",
    "libgtk-3-0",
    "libnspr4",
    "libnss3",
    "libwayland-client0",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "libxrandr2",
    "xdg-utils",
    "libu2f-udev",
    "libvulkan1",
    "xvfb",
    "wget",
    "chromium"
] 